config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'

  resources :docs
  authenticated :user do
    root "docs#index", as: "authenticated_root"
  end

  root 'welcome#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doc.rb
class Doc < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :docs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/docs_controller.rb
# frozen_string_literal: true

class DocsController < ApplicationController
  before_action :find_doc, only: %i[show edit destroy update]

  def index
    @docs = Doc.where(user_id: current_user).order('created_at DESC')
  end

  def show
  end

  def new
    @doc = current_user.docs.build
  end

  def create
    @doc = current_user.docs.build(doc_params)
    if @doc.save
      redirect_to @doc
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @doc.update(doc_params)
      redirect_to @doc
    else
      render 'edit'
    end
  end

  def destroy
    @doc.destroy
    redirect_to docs_path
  end

  private

  def find_doc
    @doc = Doc.find(params[:id])
  end

  def doc_params
    params.require(:doc).permit(:title, :content)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/docs/_form.html.erb
<%= simple_form_for @doc do |f| %>
<%= f.input :title %>
<%= f.input :content %>
<%= f.button :submit %>
<% end %>

app/views/docs/edit.html.erb
<div class="wrapper_with_padding">
  <h1>Fix Doc!</h1>

  <%= render 'form', doc: @doc %>

  <%= link_to "Cancel", doc_path %>
</div>

app/views/docs/index.html.erb
<% @docs.each do |doc| %>
  <div class="wrapper_with_padding">
    <div id="docs">
      <div class="doc">

        <div class="title"><%= link_to doc.title, doc %></div>


        <p><%= time_ago_in_words(doc.created_at) %></p>
        <p><%= truncate(doc.content, length: 50) %></p>
      </div>
    </div>
  </div>
<% end %>
<button><%= link_to "Create Doc", new_doc_path %></button>

app/views/docs/new.html.erb
<div class="wrapper_with_padding">

  <h1>New docs</h1>

  <%= render 'form', doc: @doc %>
</div>

app/views/docs/show.html.erb
<div class="wrapper_with_padding">
<div id="doc_show">
  <div class="title"> <%= @doc.title  %></div>
  <p> <%=  @doc.content%> </p>

  <div>
    <%= link_to "All Docs", docs_path, class: "button" %>
    <%= link_to "Fix Doc", edit_doc_path(@doc), class: "button" %>
    <%= link_to "Trash it", doc_path(@doc), method: :delete, data: {confirm: "Are you sure?"}, class: "button" %>
  </div>
</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<style>
    .index{
        color: whitesmoke;
    }
</style>
<head>
  <title>Keep</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<header>
  <header_inner>

      <%= link_to "Keep App" , root_path, class: "index"  %>

    <nav>
      <% if user_signed_in? %>

          <%= link_to "Create Doc", new_doc_path, class: "index" %>

          <%= link_to "Sign Out", destroy_user_session_path, method: :delete , class: "index" %>
      <% else %>

          <%= link_to "Log In", new_user_session_path, class: "index" %>
      <% end %>
    </nav>
  </header_inner>
</header>


<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>
</body>
</html>

app/views/welcome/index.html.erb
<div class="banner" style="padding:15px; text-align:center;">
  <div class="banner-content">
    <h1>Keep App </h1>
    <p> Keep Everything in your space </p>
    <btn class="btn btn-primary"><%= link_to "Enter", new_user_registration_path %></btn>

  </div>
</div>